
image_topic: "/cam0/image_raw"
point_feature_cfg:
        H: 480 #480 # Input image height
        W: 752 #752 # Input image width
        min_cnt: 120

        extract_method: "superpoint"    # supported: [superpoint, orb, r2d2]
        superpoint:
                weights_path: '/home/nnplvio_r2d2_ws/src/sp-sold2-vins/feature_tracker/scripts/utils_point/superpoint/superpoint_v1.pth'
                nms_dist: 4    # Non Maximum Suppression (NMS) distance
                conf_thresh: 0.015 #0.015 # Detector confidence threshold
                nn_thresh: 0.7 # Descriptor matching threshold 
                cuda: true # Use cuda GPU to speed up network processing speed
        r2d2:
                weights_path: "/home/nnplvio_r2d2_ws/src/sp-sold2-vins/feature_tracker/scripts/utils_point/r2d2/r2d2_WASF_N16.pt"
                reliability_thr: 0.99
                repeatability_thr: 0.99
                border_remove: 8 # Remove points this close to the border.
                cuda: True
                thresh: 0.99
       
        match_method: "nnm"       # supported: [nnm，superglue, knn, r2d2]
        nnm:
                max_length: 5  # Maximum length of point tracks
                nn_thresh: 0.8 # Descriptor matching threshold
        knn:
                thresh: 0.75
        
        superglue: 
                sinkhorn_iterations: 20
                match_threshold: 0.7
                weight_path: "/home/nnplvio_r2d2_ws/src/sp-sold2-vins/feature_tracker/scripts/utils_point/superglue/superglue_outdoor.pth"

line_feature_cfg:
        H: 480 #480 # Input image height
        W: 752 #752 # Input image width
        min_cnt: 60
        num_samples: 5
        extract_method: "lcnn" # supported: [sold2, lcnn, tplsd]
        sold2:
                min_dist_pts: 8
                line_score: false
                sampling: "regular"
        lcnn:
                weight_path: "/home/nnplvio_r2d2_ws/src/sp-sold2-vins/feature_tracker/scripts/utils_line/lcnn/312k.pth.tar"
                backbone: stacked_hourglass
                depth: 4
                num_stacks: 2
                num_blocks: 1
                head_size: [[2], [1], [2]]
                img_mean: [109.730, 103.832, 98.681]
                img_stddev: [22.275, 22.124, 23.229]
                loss_weight:
                        jmap: 8.0
                        lmap: 0.5
                        joff: 0.25
                        lpos: 1
                        lneg: 1

                sampler:
                        ## static sampler
                        n_stc_posl: 300
                        n_stc_negl: 40

                        ## dynamic sampler
                        n_dyn_junc: 300
                        n_dyn_posl: 300
                        n_dyn_negl: 80
                        n_dyn_othr: 600

                        # LOIPool layer parameters
                        n_pts0: 32
                        n_pts1: 8

                        # line verification network parameters
                        dim_loi: 128
                        dim_fc: 1024

                        # maximum junction and line outputs
                        n_out_junc: 250
                        n_out_line: 2500

                        # additional ablation study parameters
                        use_cood: 0
                        use_slop: 0
                        use_conv: 0

                        # junction threashold for evaluation (See #5)
                        eval_junc_thres: 0.04
                        
        tplsd:
                model: "tplite"

        match_method: "wunsch"  # supported: [wunsch, knn]
        wunsch:
                cross_check: True
                top_k_candidates: 10
                line_score: false
        knn:
                thresh: 0.75
        
#camera calibration 
camera_cfg:
        model_type: PINHOLE
        camera_name: camera
        image_height: 480 #480
        image_width: 752 #752
        distortion_parameters:
                k1: -2.917e-01
                k2: 8.228e-02
                p1: 5.333e-05
                p2: -1.578e-04
        projection_parameters:
                fx: 4.616e+02
                fy: 4.603e+02
                cx: 3.630e+02
                cy: 2.481e+02


